"""limit_fields_for_connector_and_transaction

Revision ID: 0002
Revises: 0001
Create Date: 2023-12-13 17:53:52.328464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connectors', sa.Column('latest_limit', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'connectors', ['id', 'charge_point_id'])
    op.add_column('transactions', sa.Column('limit', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'limit')
    op.drop_constraint(None, 'connectors', type_='unique')
    op.drop_column('connectors', 'latest_limit')
    # ### end Alembic commands ###
