"""track_id_for_transaction

Revision ID: 0003
Revises: 0002
Create Date: 2023-12-14 10:25:47.451962

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '0003'
down_revision = '0002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('track_id', sa.String(), nullable=False))
    op.create_index(op.f('ix_transactions_track_id'), 'transactions', ['track_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_track_id'), table_name='transactions')
    op.drop_column('transactions', 'track_id')
    # ### end Alembic commands ###
