"""connector_id_for_transaction

Revision ID: 0004
Revises: 0003
Create Date: 2023-09-30 05:39:43.518254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0004'
down_revision = '0003'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('operators', 'first_name',
               existing_type=sa.VARCHAR(length=24),
               nullable=False)
    op.alter_column('operators', 'last_name',
               existing_type=sa.VARCHAR(length=24),
               nullable=False)
    op.alter_column('operators', 'address',
               existing_type=sa.VARCHAR(length=48),
               nullable=False)
    op.add_column('transactions', sa.Column('connector', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'connector')
    op.alter_column('operators', 'address',
               existing_type=sa.VARCHAR(length=48),
               nullable=True)
    op.alter_column('operators', 'last_name',
               existing_type=sa.VARCHAR(length=24),
               nullable=True)
    op.alter_column('operators', 'first_name',
               existing_type=sa.VARCHAR(length=24),
               nullable=True)
    # ### end Alembic commands ###
