"""garages_table

Revision ID: 0005
Revises: 0004
Create Date: 2023-10-11 19:31:11.725028

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '0005'
down_revision = '0004'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('garages',
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('address', sa.String(), nullable=False),
                    sa.Column('grid_provider', sa.String(), nullable=False),
                    sa.Column('contact', sa.String(), nullable=False),
                    sa.Column('phone', sa.String(), nullable=False),
                    sa.Column('id', sa.String(length=20), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('is_active', sa.Boolean(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('address')
                    )
    op.create_index(op.f('ix_garages_id'), 'garages', ['id'], unique=True)
    op.add_column('charge_points', sa.Column('garage_id', sa.String(), nullable=False))
    op.drop_constraint('charge_points_serial_number_key', 'charge_points', type_='unique')
    op.create_foreign_key(None, 'charge_points', 'garages', ['garage_id'], ['id'])
    op.add_column('drivers', sa.Column('garage_id', sa.String(), nullable=False))
    op.create_foreign_key(None, 'drivers', 'garages', ['garage_id'], ['id'])
    op.add_column('operators', sa.Column('garage_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'operators', 'garages', ['garage_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'operators', type_='foreignkey')
    op.drop_column('operators', 'garage_id')
    op.drop_constraint(None, 'drivers', type_='foreignkey')
    op.drop_column('drivers', 'garage_id')
    op.drop_constraint(None, 'charge_points', type_='foreignkey')
    op.create_unique_constraint('charge_points_serial_number_key', 'charge_points', ['serial_number'])
    op.drop_column('charge_points', 'garage_id')
    op.drop_index(op.f('ix_garages_id'), table_name='garages')
    op.drop_table('garages')
    # ### end Alembic commands ###
