"""new_fields_for_garages_table

Revision ID: 0007
Revises: 0006
Create Date: 2023-10-17 08:04:49.352562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0007'
down_revision = '0006'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('garages', sa.Column('city', sa.String(), nullable=False))
    op.add_column('garages', sa.Column('street', sa.String(), nullable=False))
    op.add_column('garages', sa.Column('email', sa.String(), nullable=False))
    op.add_column('garages', sa.Column('postnummer', sa.String(), nullable=False))
    op.drop_constraint('garages_address_key', 'garages', type_='unique')
    op.drop_column('garages', 'address')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('garages', sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_unique_constraint('garages_address_key', 'garages', ['address'])
    op.drop_column('garages', 'postnummer')
    op.drop_column('garages', 'email')
    op.drop_column('garages', 'street')
    op.drop_column('garages', 'city')
    # ### end Alembic commands ###
