"""removed_redundant_fields_from_garages

Revision ID: 0009
Revises: 0008
Create Date: 2023-10-20 09:24:14.986643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0009'
down_revision = '0008'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('garages', 'grid_provider')
    op.drop_column('garages', 'postnummer')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('garages', sa.Column('postnummer', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('garages', sa.Column('grid_provider', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
