"""grid_providers_table

Revision ID: 0010
Revises: 0009
Create Date: 2023-10-20 09:43:23.358144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0010'
down_revision = '0009'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grid_providers',
    sa.Column('postnummer', sa.String(), nullable=False),
    sa.Column('region', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('daily_rate', sa.Numeric(precision=2, scale=2), nullable=True),
    sa.Column('nightly_rate', sa.Numeric(precision=2, scale=2), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('postnummer')
    )
    op.create_index(op.f('ix_grid_providers_id'), 'grid_providers', ['id'], unique=True)
    op.add_column('garages', sa.Column('grid_provider_id', sa.String(), nullable=False))
    op.create_foreign_key(None, 'garages', 'grid_providers', ['grid_provider_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'garages', type_='foreignkey')
    op.drop_column('garages', 'grid_provider_id')
    op.drop_index(op.f('ix_grid_providers_id'), table_name='grid_providers')
    op.drop_table('grid_providers')
    # ### end Alembic commands ###
