"""index_for_grid_providers_postnummer_field

Revision ID: 0011
Revises: 0010
Create Date: 2023-10-20 10:36:06.188037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0011'
down_revision = '0010'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('grid_providers_postnummer_key', 'grid_providers', type_='unique')
    op.create_index(op.f('ix_grid_providers_postnummer'), 'grid_providers', ['postnummer'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_grid_providers_postnummer'), table_name='grid_providers')
    op.create_unique_constraint('grid_providers_postnummer_key', 'grid_providers', ['postnummer'])
    # ### end Alembic commands ###
