"""index_for_grid_providers_name_field

Revision ID: 0012
Revises: 0011
Create Date: 2023-10-20 10:36:52.659768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0012'
down_revision = '0011'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_grid_providers_name'), 'grid_providers', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_grid_providers_name'), table_name='grid_providers')
    # ### end Alembic commands ###
