"""government_rebates_table

Revision ID: 0013
Revises: 0012
Create Date: 2023-10-20 14:45:18.208027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0013'
down_revision = '0012'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('government_rebates',
    sa.Column('value', sa.Numeric(precision=2, scale=10), nullable=False),
    sa.Column('garage_id', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['garage_id'], ['garages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_government_rebates_id'), 'government_rebates', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_government_rebates_id'), table_name='government_rebates')
    op.drop_table('government_rebates')
    # ### end Alembic commands ###
