"""rates_for_garages_table

Revision ID: 0014
Revises: 0013
Create Date: 2023-10-21 16:04:26.402324

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '0014'
down_revision = '0013'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('garages', sa.Column('daily_rate', sa.Numeric(precision=2, scale=2), nullable=True))
    op.add_column('garages', sa.Column('nightly_rate', sa.Numeric(precision=2, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('garages', 'nightly_rate')
    op.drop_column('garages', 'daily_rate')
    # ### end Alembic commands ###
