"""cascade_delete_for_connectors

Revision ID: 0016
Revises: 0015
Create Date: 2023-10-28 10:00:34.473598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0016'
down_revision = '0015'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'connectors', ['id', 'charge_point_id'])
    op.drop_constraint('connectors_charge_point_id_fkey', 'connectors', type_='foreignkey')
    op.create_foreign_key(None, 'connectors', 'charge_points', ['charge_point_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'connectors', type_='foreignkey')
    op.create_foreign_key('connectors_charge_point_id_fkey', 'connectors', 'charge_points', ['charge_point_id'], ['id'])
    op.drop_constraint(None, 'connectors', type_='unique')
    # ### end Alembic commands ###
