"""extra_type_for_connectors

Revision ID: 0017
Revises: 0016
Create Date: 2023-10-28 10:36:43.507344

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = '0017'
down_revision = '0016'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
    CREATE TYPE chargepointerrorcode AS ENUM ('connector_lock_failure', 'ev_communication_error', 'ground_failure', 'high_temperature', 'internal_error', 'local_list_conflict', 'no_error', 'other_error', 'over_current_failure', 'over_voltage', 'power_meter_failure', 'power_switch_failure', 'reader_failure', 'reset_failure', 'under_voltage', 'weak_signal');
    """)


def downgrade() -> None:
    pass
