"""extra_fields_for_connectors

Revision ID: 0018
Revises: 0017
Create Date: 2023-10-28 10:40:01.759876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0018'
down_revision = '0017'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connectors', sa.Column('status', sa.Enum('available', 'preparing', 'charging', 'suspended_evse', 'suspended_ev', 'finishing', 'reserved', 'unavailable', 'faulted', name='chargepointstatus'), nullable=True))
    op.add_column('connectors', sa.Column('error_code', sa.Enum('connector_lock_failure', 'ev_communication_error', 'ground_failure', 'high_temperature', 'internal_error', 'local_list_conflict', 'no_error', 'other_error', 'over_current_failure', 'over_voltage', 'power_meter_failure', 'power_switch_failure', 'reader_failure', 'reset_failure', 'under_voltage', 'weak_signal', name='chargepointerrorcode'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('connectors', 'error_code')
    op.drop_column('connectors', 'status')
    # ### end Alembic commands ###
