"""spot_prices_table

Revision ID: 0019
Revises: 0018
Create Date: 2023-10-30 12:12:25.279831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0019'
down_revision = '0018'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spot_prices',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('hourly_prices', sa.ARRAY(sa.Numeric(scale=2)), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date')
    )
    op.create_index(op.f('ix_spot_prices_id'), 'spot_prices', ['id'], unique=True)
    op.drop_index('ix_charge_points_id', table_name='charge_points')
    op.create_index(op.f('ix_charge_points_id'), 'charge_points', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_charge_points_id'), table_name='charge_points')
    op.create_index('ix_charge_points_id', 'charge_points', ['id'], unique=False)
    op.drop_index(op.f('ix_spot_prices_id'), table_name='spot_prices')
    op.drop_table('spot_prices')
    # ### end Alembic commands ###
