"""complex_unique_contraint_for_charge_point

Revision ID: 0019
Revises: 0018
Create Date: 2023-10-29 13:36:24.801666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0019'
down_revision = '0018'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('charge_points', sa.Column('_id', sa.String(), nullable=False))
    op.drop_index('ix_charge_points_id', table_name='charge_points')
    op.create_index(op.f('ix_charge_points__id'), 'charge_points', ['_id'], unique=True)
    op.create_unique_constraint(None, 'charge_points', ['id', 'garage_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'charge_points', type_='unique')
    op.drop_index(op.f('ix_charge_points__id'), table_name='charge_points')
    op.create_index('ix_charge_points_id', 'charge_points', ['id'], unique=False)
    op.drop_column('charge_points', '_id')
    # ### end Alembic commands ###
