"""period_field_for_rebates_table

Revision ID: 0020
Revises: 0019
Create Date: 2023-11-03 21:59:04.409934

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '0020'
down_revision = '0019'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('government_rebates', sa.Column('period', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('government_rebates', 'period')
    # ### end Alembic commands ###
