"""role_for_users

Revision ID: 0024
Revises: 0023
Create Date: 2023-11-28 17:10:33.555814

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '0024'
down_revision = '0023'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""CREATE TYPE role AS ENUM ('resident', 'employee');""")
    op.add_column('drivers', sa.Column('role', sa.Enum('resident', 'employee', name='role'), nullable=True))
    op.add_column('operators', sa.Column('role', sa.Enum('resident', 'employee', name='role'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('operators', 'role')
    op.drop_column('drivers', 'role')
    # ### end Alembic commands ###
