"""password_for_all_persons

Revision ID: 0025
Revises: 0024
Create Date: 2023-11-28 17:27:14.487391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0025'
down_revision = '0024'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drivers', sa.Column('password', sa.String(length=124), nullable=True))
    op.alter_column('operators', 'password',
               existing_type=sa.VARCHAR(length=124),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('operators', 'password',
               existing_type=sa.VARCHAR(length=124),
               nullable=False)
    op.drop_column('drivers', 'password')
    # ### end Alembic commands ###
